name: C/C++ CI



on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2
    
    - name: uninstall uncorrect version of mingw
      run: | 
         choco uninstall mingw --force
         choco uninstall strawberryperl --force
    
    - name: install correct version of mingw
      uses:  msys2/setup-msys2@v2
      with: 
           msystem: MINGW32
           path-type: minimal
           install: msys2-devel base-devel mingw-w64-i686-toolchain msys2-runtime-devel

    - name: download qt
      run: ./qt.download.bat 6.4 6.4.1    
    
    - name: configure-qt
      shell: msys2 {0}
      run: ./qt.config.bat 6.4 6.4.1
    - name: make-qt
      shell: msys2 {0}
      run: ./qt.make.bat 6.4 6.4.1


